In [6]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\Ruban\Downloads\clean_weather.csv")
df

Unnamed: 0  tmax  tmin  rain  tmax_tomorrow
0      1970-01-01  60.0  35.0   0.0           52.0
1      1970-01-02  52.0  39.0   0.0           52.0
2      1970-01-03  52.0  35.0   0.0           53.0
3      1970-01-04  53.0  36.0   0.0           52.0
4      1970-01-05  52.0  35.0   0.0           50.0
...           ...   ...   ...   ...            ...
13504  2022-11-22  62.0  35.0   0.0           67.0
13505  2022-11-23  67.0  38.0   0.0           66.0
13506  2022-11-24  66.0  41.0   0.0           70.0
13507  2022-11-25  70.0  39.0   0.0           62.0
13508  2022-11-26  62.0  41.0   0.0           64.0

[13509 rows x 5 columns]

In [4]:
df["tmax"]

0        60.0
1        52.0
2        52.0
3        53.0
4        52.0
         ... 
13504    62.0
13505    67.0
13506    66.0
13507    70.0
13508    62.0
Name: tmax, Length: 13509, dtype: float64

In [8]:
df["tmax"].to_numpy()[np.newaxis,:]

array([[60., 52., 52., ..., 66., 70., 62.]])

In [19]:
np.random.seed(42)

i_weight = np.random.rand(1, 2)
h_weight = np.random.rand(2, 2)
o_weight = np.random.rand(2, 1)

temps = df["tmax"].head(3).to_numpy()
temps

array([60., 52., 52.])

In [20]:
x0 = temps[0].reshape(1, 1)
x1 = temps[1].reshape(1, 1)
x2 = temps[2].reshape(1, 1)
x0, x1, x2

(array([[60.]]), array([[52.]]), array([[52.]]))

In [22]:
xi_0 = x0 @ i_weight
xi_0

array([[22.47240713, 57.04285838]])

In [24]:
xh_0 = np.maximum(0, xi_0)
xh_0

array([[22.47240713, 57.04285838]])

In [25]:
xo_0 = xh_0 @ o_weight
xo_0

array([[50.7144418]])

In [26]:
xi_1 = x1 @ i_weight
xi_1

array([[19.47608618, 49.43714393]])

In [27]:
xh = xh_0 @ h_weight
xh

array([[25.34941509, 22.35167052]])

In [28]:
xh_1 = np.maximum(0, xh + xi_1)
xh_1

array([[44.82550127, 71.78881445]])

In [29]:
xo_1 = xh_1 @ o_weight
xo_1

array([[64.78538565]])

In [30]:
xi_2 = x2 @ i_weight
xi_2

array([[19.47608618, 49.43714393]])

In [31]:
xh = xh_1 @ h_weight
xh

array([[44.0123886 , 38.03382832]])

In [32]:
xh_2 = np.maximum(0, xh + xi_2)
xh_2

array([[63.48847478, 87.47097225]])

In [33]:
xo_2 = xh_2 @ o_weight
xo_2

array([[79.45290956]])

In [47]:
np.random.seed(0)
i_weight = np.random.rand(1, 5)
h_weight = np.random.rand(5, 5)
h_bias = np.random.rand(1, 5)

o_weight = np.random.rand(5, 1) * 50
o_bias = np.random.rand(1, 1)

In [48]:
o_weight, o_bias

(array([[30.88177485],
        [30.60478614],
        [30.84669984],
        [47.18740393],
        [34.09101496]]),
 array([[0.3595079]]))

In [49]:
outputs = np.zeros(3)
hiddens = np.zeros((3, 5))
prev_hidden = None
sequence = df['tmax'].head(3).to_numpy()

for i in range(3):
    
    x = sequence[i].reshape(1, 1)
    
    xi = x @ i_weight
    if prev_hidden is None:
        xh = xi
    else:
        xh = prev_hidden @ h_weight + xi + h_bias
    
    xh = np.tanh(xh)
    prev_hidden = xh
    hiddens[i, ] = xh
    outputs[i] = xh @ o_weight + o_bias

C:\Users\Ruban\AppData\Local\Temp\ipykernel_14432\2588747601.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  outputs[i] = xh @ o_weight + o_bias


In [50]:
outputs

array([173.97118762, 173.97118762, 173.97118762])

In [1]:
import numpy as np
i_weight = np.random.randn(2, 8)   # input feature size x hidden state  size
xi = np.array([ 
    np.array([2, 2]),
    np.array([3, 3]),
    np.array([4, 4]),
    np.array([5, 5]),
])                                 # sequence length x input size
previous_hid = None
hidd_wei = np.random.rand(8, 8)
hidden_bi = np.zeros((1, 8))      # Based on state size

o_weight = np.random.randn(8, 4)  # hidden_state x output_size 
o_bias = np.zeros((1, 4))         # Based on output size


In [2]:
xi[0].reshape(1, 2)

array([[2, 2]])

In [3]:
all_hidden = np.zeros((max(xi.shape), 8))         # sequence length x hidden state size
output = np.zeros((4, 4))             # sequence length x output size
y_true = np.array([[10, 11, 12, 13],
                   [14, 15, 16, 17],
                   [18, 19, 20, 21],
                   [22, 23, 24, 25]])

In [4]:
for i in range(max(xi.shape)):
    in_x = xi[i].reshape(1, 2)
    x_in = in_x @ i_weight
    
    if previous_hid is None:
        xh = x_in
    else:
        xh = x_in + hidden_bi + previous_hid @ hidd_wei
    xh = np.tanh(xh)
    all_hidden[i, ] = xh
    output[i,] = xh @ o_weight + o_bias

In [5]:
output

array([[ 1.48820903,  1.31859414, -0.03889734,  1.46376029],
       [ 1.52487403,  1.53724859, -0.41833846,  1.433718  ],
       [ 1.59287705,  1.71426035, -0.62261063,  1.3634284 ],
       [ 1.68841093,  1.85427038, -0.71953675,  1.29764741]])

In [6]:
all_hidden

array([[-0.44066419, -0.99775651,  0.13582423,  0.11407005, -0.99676402,
        -0.6936356 ,  0.98527205, -0.85455864],
       [-0.61041473, -0.99992474,  0.20217888,  0.170181  , -0.99986953,
        -0.85712122,  0.99872287, -0.95702001],
       [-0.73801667, -0.99999748,  0.26672781,  0.22520967, -0.99999475,
        -0.93663006,  0.99988993, -0.98777463],
       [-0.82828127, -0.99999992,  0.32896936,  0.27883809, -0.99999979,
        -0.97254804,  0.99999052, -0.99656125]])

In [10]:
np.mean((y_true - output) ** 2) 

294.0239085691826

In [9]:
d_loss = output - y_true
d_loss

array([[ -8.51179097,  -9.68140586, -12.03889734, -11.53623971],
       [-12.47512597, -13.46275141, -16.41833846, -15.566282  ],
       [-16.40712295, -17.28573965, -20.62261063, -19.6365716 ],
       [-20.31158907, -21.14572962, -24.71953675, -23.70235259]])

In [13]:
d_o_weight = np.zeros_like(o_weight)
d_o_bias = np.zeros_like(o_bias)
d_i_weight = np.zeros_like(i_weight)
d_h_weight = np.zeros_like(hidd_wei)
d_h_bias = np.zeros_like(hidden_bi)

next_hiddent = np.zeros((1, 8))

In [ ]:
for i in reversed(range(4)):
    xh = all_hidden[i].reshape(1, 8)
    d_out = d_loss[i].reshape(1, 4)
    
    d_o_weight += xh.T @ d_out
    d_o_bias += d_out
    
    

[[-0.82828127 -0.99999992  0.32896936  0.27883809 -0.99999979 -0.97254804
   0.99999052 -0.99656125]] [[-20.31158907 -21.14572962 -24.71953675 -23.70235259]]
[[-0.73801667 -0.99999748  0.26672781  0.22520967 -0.99999475 -0.93663006
   0.99988993 -0.98777463]] [[-16.40712295 -17.28573965 -20.62261063 -19.6365716 ]]
[[-0.61041473 -0.99992474  0.20217888  0.170181   -0.99986953 -0.85712122
   0.99872287 -0.95702001]] [[-12.47512597 -13.46275141 -16.41833846 -15.566282  ]]
[[-0.44066419 -0.99775651  0.13582423  0.11407005 -0.99676402 -0.6936356
   0.98527205 -0.85455864]] [[ -8.51179097  -9.68140586 -12.03889734 -11.53623971]]


In [8]:
import numpy as np

# Input sequence (2 time steps)
x = [np.array([[1, 2]]), np.array([[0, 1]])]  # (1x2) each

# True target outputs (we’ll use MSE loss)
target = [np.array([[0.5]]), np.array([[0.8]])]  # (1x1) each

# Weights
W_ih = np.array([[0.1, 0.2],  # input → hidden
                 [0.3, 0.4]])
W_hh = np.array([[0.5, 0.6],  # hidden → hidden
                 [0.7, 0.8]])
b_h = np.array([[0.0, 0.0]])  # hidden bias

W_ho = np.array([[1.0],       # hidden → output
                 [2.0]])
b_o = np.array([[0.0]])       # output bias
h_t_1 = np.array([[0, 0]])


In [9]:
z_0 = x[0] @ W_ih + h_t_1 @ W_ih + b_h
z_0

array([[0.7, 1. ]])

In [11]:
a_0 = np.tanh(z_0)
a_0

array([[0.60436778, 0.76159416]])

In [12]:
y_0 = a_0 @ W_ho + b_o
y_0

array([[2.12755609]])

In [13]:
loss = 1 / 2 * ((y_0 - target[0]) ** 2)
loss

array([[1.32446941]])

In [14]:
z_1 = x[1] @ W_ih + a_0 @ W_hh + b_h
z_1

array([[1.1352998 , 1.37189599]])

In [15]:
a_1 = np.tanh(z_1)
a_1

array([[0.81282533, 0.87912357]])

In [16]:
y_1 = a_1 @ W_ho + b_o
y_1

array([[2.57107247]])

In [17]:
loss1 = 1 / 2 * ((y_1 - target[1]) ** 2)
loss1

array([[1.56834884]])

In [19]:
d_loss = y_1 - target[1]  # loss w.r.t y_1
d_loss

array([[1.77107247]])

In [21]:
# loss of y_1 w.r.t a_1
# y_1 = a_1 . w_ho + b_o
# y_ = w_ho
d_loss_y_1 = d_loss @ W_ho.T
d_loss_y_1

array([[1.77107247, 3.54214493]])

In [24]:
# loss y_1 w.r.t w_ho
# y_1 = a_1 . w_ho + b_o


d_loss_w_ho = a_1.T @ d_loss
d_loss_w_ho

array([[1.43957256],
       [1.55699155]])

In [25]:
d_loss_b_o = d_loss
d_loss_b_o

array([[1.77107247]])

In [29]:
# loss of a_1 w.r.t z1
# a_1 = tanh(z1)
# d_a_1 = 1 - tanh(z1) ** 2
# d_a_1 = 1 - a_1 ** 2

d_loss_a1 = d_loss_y_1 * (1 - (a_1) ** 2)
d_loss_a1

array([[0.60095143, 0.80456899]])

In [52]:
import numpy as np

# Input sequence (2 time steps)
x = [np.array([[1, 2]]), np.array([[0, 1]])]  # (1x2) each

# True target outputs (we’ll use MSE loss)
target = [np.array([[0.5]]), np.array([[0.8]])]  # (1x1) each

# Weights
W_ih = np.array([[0.1, 0.2],  # input → hidden
                 [0.3, 0.4]])
W_hh = np.array([[0.5, 0.6],  # hidden → hidden
                 [0.7, 0.8]])
b_h = np.array([[0.0, 0.0]])  # hidden bias

W_ho = np.array([[1.0],       # hidden → output
                 [2.0]])
b_o = np.array([[0.0]])       # output bias
h_t_1 = np.array([[0, 0]])

all_hidden = np.zeros((2, 2))
output = np.zeros((2, 1))
sequence = 2
for i in range(sequence):
    z1 = x[i] @ W_ih + h_t_1 @ W_hh + b_h
    h = np.tanh(z1)
    all_hidden[i, ] = h
    y = h @ W_ho + b_o
    output[i, ] = y
    h_t_1 = h
    
    
next_hidden = np.zeros_like(h_t_1)
d_W_ih = np.zeros_like(W_ih)
d_W_hh = np.zeros_like(W_hh)
d_b_h = np.zeros_like(b_h)
d_W_ho = np.zeros_like(W_ho)
d_b_o = np.zeros_like(b_o)

loss = 1/2 * ((output.reshape(-1, 1) - np.array(target).reshape(-1, 1)) ** 2)
print(loss)
d_loss = (output.reshape(-1, 1) - np.array(target).reshape(-1, 1))
for i in range(sequence - 1, -1, -1):
    y_loss = d_loss[i].reshape(1, 1)
    h_l = all_hidden[i].reshape(1, -1)
    d_W_ho += h_l.T @ y_loss
    d_b_o += y_loss
    
    xh = 1 - (all_hidden[i] ** 2)
    hidden_loss = (y_loss @ W_ho.T)
    update_hidden_loss = hidden_loss * xh
    
    d_W_ih += x[i].T @ update_hidden_loss
    d_W_hh += next_hidden.T @ update_hidden_loss
    d_b_h += update_hidden_loss
    
    next_hidden = update_hidden_loss @ W_hh.T
    

[[1.32446941]
 [1.56834884]]


In [ ]:
# loss w.r.t output
# loss of output w.r.t w_ho
# loss of output w.r.t w_bo
# loss of output w.r.t hidden state
# loss of hidden state w.r.t z1
z1 = x . d_W_ih + prev_hidden . d_W_hh + d_b_h

In [47]:
y_loss

array([[3.13669768]])

In [45]:
1 - (all_hidden[i] ** 2)

array([0.33931499, 0.22714175])