In [6]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\Ruban\Downloads\clean_weather.csv")
df

Unnamed: 0  tmax  tmin  rain  tmax_tomorrow
0      1970-01-01  60.0  35.0   0.0           52.0
1      1970-01-02  52.0  39.0   0.0           52.0
2      1970-01-03  52.0  35.0   0.0           53.0
3      1970-01-04  53.0  36.0   0.0           52.0
4      1970-01-05  52.0  35.0   0.0           50.0
...           ...   ...   ...   ...            ...
13504  2022-11-22  62.0  35.0   0.0           67.0
13505  2022-11-23  67.0  38.0   0.0           66.0
13506  2022-11-24  66.0  41.0   0.0           70.0
13507  2022-11-25  70.0  39.0   0.0           62.0
13508  2022-11-26  62.0  41.0   0.0           64.0

[13509 rows x 5 columns]

In [4]:
df["tmax"]

0        60.0
1        52.0
2        52.0
3        53.0
4        52.0
         ... 
13504    62.0
13505    67.0
13506    66.0
13507    70.0
13508    62.0
Name: tmax, Length: 13509, dtype: float64

In [8]:
df["tmax"].to_numpy()[np.newaxis,:]

array([[60., 52., 52., ..., 66., 70., 62.]])

In [19]:
np.random.seed(42)

i_weight = np.random.rand(1, 2)
h_weight = np.random.rand(2, 2)
o_weight = np.random.rand(2, 1)

temps = df["tmax"].head(3).to_numpy()
temps

array([60., 52., 52.])

In [20]:
x0 = temps[0].reshape(1, 1)
x1 = temps[1].reshape(1, 1)
x2 = temps[2].reshape(1, 1)
x0, x1, x2

(array([[60.]]), array([[52.]]), array([[52.]]))

In [22]:
xi_0 = x0 @ i_weight
xi_0

array([[22.47240713, 57.04285838]])

In [24]:
xh_0 = np.maximum(0, xi_0)
xh_0

array([[22.47240713, 57.04285838]])

In [25]:
xo_0 = xh_0 @ o_weight
xo_0

array([[50.7144418]])

In [26]:
xi_1 = x1 @ i_weight
xi_1

array([[19.47608618, 49.43714393]])

In [27]:
xh = xh_0 @ h_weight
xh

array([[25.34941509, 22.35167052]])

In [28]:
xh_1 = np.maximum(0, xh + xi_1)
xh_1

array([[44.82550127, 71.78881445]])

In [29]:
xo_1 = xh_1 @ o_weight
xo_1

array([[64.78538565]])

In [30]:
xi_2 = x2 @ i_weight
xi_2

array([[19.47608618, 49.43714393]])

In [31]:
xh = xh_1 @ h_weight
xh

array([[44.0123886 , 38.03382832]])

In [32]:
xh_2 = np.maximum(0, xh + xi_2)
xh_2

array([[63.48847478, 87.47097225]])

In [33]:
xo_2 = xh_2 @ o_weight
xo_2

array([[79.45290956]])

In [47]:
np.random.seed(0)
i_weight = np.random.rand(1, 5)
h_weight = np.random.rand(5, 5)
h_bias = np.random.rand(1, 5)

o_weight = np.random.rand(5, 1) * 50
o_bias = np.random.rand(1, 1)

In [48]:
o_weight, o_bias

(array([[30.88177485],
        [30.60478614],
        [30.84669984],
        [47.18740393],
        [34.09101496]]),
 array([[0.3595079]]))

In [49]:
outputs = np.zeros(3)
hiddens = np.zeros((3, 5))
prev_hidden = None
sequence = df['tmax'].head(3).to_numpy()

for i in range(3):
    
    x = sequence[i].reshape(1, 1)
    
    xi = x @ i_weight
    if prev_hidden is None:
        xh = xi
    else:
        xh = prev_hidden @ h_weight + xi + h_bias
    
    xh = np.tanh(xh)
    prev_hidden = xh
    hiddens[i, ] = xh
    outputs[i] = xh @ o_weight + o_bias

C:\Users\Ruban\AppData\Local\Temp\ipykernel_14432\2588747601.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  outputs[i] = xh @ o_weight + o_bias


In [50]:
outputs

array([173.97118762, 173.97118762, 173.97118762])

In [ ]:
import numpy as np
i_weight = np.random.randn(2, 8)   # input feature size x hidden state  size
xi = np.array([ 
    np.array([2, 2]),
    np.array([3, 3]),
    np.array([4, 4]),
    np.array([5, 5]),
])                                 # sequence length x input size
previous_hid = None
hidd_wei = np.random.rand(8, 8)
hidden_bi = np.zeros((1, 8))      # Based on state size

o_weight = np.random.randn(8, 4)  # hidden_state x output_size 
o_bias = np.zeros((1, 4))         # Based on output size


In [10]:
xi[0].reshape(1, 2)

array([[2, 2]])

In [ ]:
all_hidden = np.zeros((max(xi.shape), 8))         # sequence length x hidden state size
output = np.zeros((4, 4))                         # sequence length x output size

In [25]:
for i in range(max(xi.shape)):
    in_x = xi[i].reshape(1, 2)
    x_in = in_x @ i_weight
    
    if previous_hid is None:
        xh = x_in
    else:
        xh = x_in + hidden_bi + previous_hid @ hidd_wei
    xh = np.tanh(xh)
    all_hidden[i, ] = xh
    output[i,] = xh @ o_weight + o_bias

In [26]:
output

array([[-2.11752224, -1.80204735, -3.55751103,  0.88045244],
       [-2.43638825, -2.11038609, -3.83973386,  1.0558951 ],
       [-2.59542413, -2.28821043, -4.00200501,  1.09319814],
       [-2.67029921, -2.38446572, -4.10226613,  1.08733429]])

In [27]:
all_hidden

array([[ 0.47344316,  0.73072973, -0.99966203,  0.72457193,  0.97570559,
         0.97689375, -0.999911  ,  0.9980412 ],
       [ 0.64794499,  0.88436137, -0.99999561,  0.88000859,  0.99727658,
         0.99747593, -0.99999941,  0.99993861],
       [ 0.77350613,  0.95273267, -0.99999994,  0.95025547,  0.99969763,
         0.99972681, -1.        ,  0.99999808],
       [ 0.85814056,  0.98108523, -1.        ,  0.979819  ,  0.99996647,
         0.99997046, -1.        ,  0.99999994]])